title: <p align="center"> Sanjaya Kumar Sahoo </p>
logo: /assets/img/self.jpeg

description:
  <p align="center">
  <a href="pdf/Sanjaya_Kumar_Sahoo.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/SanjayaKumarSahoo/">LinkedIn</a> |
  <a href="https://github.com/SanjayaKumarSahoo">GitHub</a>
  
  <br>
  Architecting / Building event-driven, distributed, IOT, big data, cloud-native analytics platform, 
  processing 1 billion data points every day, generating valuable insight through a proprietary algorithm, 
  Driving design/development of cloud-native micro services for platforms.
  <br>
  </p>


theme: jekyll-theme-minimal