title: <p align="center"> Sanjaya Kumar Sahoo </p>
logo: /assets/img/self.jpeg

description:
  <p align="center">
  <a href="pdf/Sanjaya_Kumar_Sahoo.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/SanjayaKumarSahoo/">LinkedIn</a> |
  <a href="https://github.com/SanjayaKumarSahoo">GitHub</a>
  <br>
  Architecting / Building event-driven, distributed, IOT, big data, cloud-native analytics platform.
  Currently working as Distinguished Technologist @ Hewlett Packard Enterprise
  <br>
  </p>
theme: jekyll-theme-minimal